version: '3.1'
services:
  app:
    build: .
    ports:
      - 4000:4000
    links: 
     - postgres
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: $NODE_ENV
    depends_on:
      - postgres
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/usr/src/app/redis
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/usr/src/app/posgres
    environment:
      POSTGRES_USERNAME: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
volumes:
  data:
  data_redis:
